modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Frontiers-PackForge/Cosmic-Rocketry/issues"
license = "Creative Commons"

[[mods]]
modId = "cosmicrocketry"
version = "${version}"
displayName = "Cosmic Rocketry"
authors = "MrQuentinet"
description = """A Simple Addon mod to add extra rocket tiers to Ad Astra

Thanks to Ad Astra for allowing us to use and modify their rocket model and textures"""
logoFile = "icon.png"

[[dependencies.cosmicrocketry]]
modId = "neoforge"
type="required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cosmicrocketry]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cosmicrocketry]]
modId = "resourcefullib"
type="required"
versionRange = "[2.4.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cosmicrocketry]]
modId = "resourcefulconfig"
type="required"
versionRange = "[2.4.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cosmicrocketry]]
modId = "botarium"
type="required"
versionRange = "[3.0.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cosmicrocketry]]
modId = "ad_astra"
type="required"
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"